language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f ./client/Dcckerfile.dev

script:
  - docker run -e CI=true lastzz/react-test npm run test

after_success:
  - docker build -t stephengrider/multi-client ./client
  - docker build -t stephengrider/multi-nginx ./nginx
  - docker build -t stephengrider/multi-server ./server
  - docker build -t stephengrider/muti-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lastzz/multi-client
  - docker push lastzz/multi-nginx
  - docker push lastzz/multi-server
  - docker push lastzz/multi-worker

