sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lastzz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lastzz/react-test npm run test

after_success:
  - docker build -t lastzz/multi-client ./client
  - docker build -t lastzz/multi-nginx ./nginx
  - docker build -t lastzz/multi-server ./server
  - docker build -t lastzz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lastzz/multi-client
  - docker push lastzz/multi-nginx
  - docker push lastzz/multi-server
  - docker push lastzz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-275896992647'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
